### ISSUE TITLE
riptide-metrics is mandatory dependency when using io.dropwizard.metrics:metrics-core in project

### ISSUE THREAD

**Issue by jmatusewicz-bringmeister** [zalando/riptide#308]
Riptide autoconfiguration assumes riptide-metrics is in classpath as soon as there is a `com.codahale.metrics.MetricRegistry` bean configured. This leads to a 
```
Caused by: java.lang.NoClassDefFoundError: org/zalando/riptide/metrics/MetricsNameGenerator
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
        ...
```
on application start.

https://github.com/zalando/riptide/blob/5efafaba5fca3e8a2d875602ecac97089541d721/riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/RiptideAutoConfiguration.java#L33

**Comment by lukasniemeier-zalando** [comment]
I guess `RiptideAutoConfiguration.MetricsConfiguration` is missing a `ConditionalOnClass(MetricsPlugin.class)`. Can you try this?

**Comment by jmatusewicz-bringmeister** [comment]
Thanks, I did it already and it solved the issue. I thought maybe riptide could auto discover a present `ObjectMapper` bean, regardless of the bean name.

**Comment by jmatusewicz-bringmeister** [comment]
Yes, that works. I prepared a PR.
