### ISSUE TITLE
java.lang.BootstrapMethodError: call site initialization exception starting from version 2.8.0

### ISSUE THREAD

**Issue by mazenmelouk** [zalando/riptide#407]
Starting from version 1.8.0 I get 'BootstrapMethodError' exception on calling `getForObject`.
Here is a [link](https://stackoverflow.com/questions/33929304/weird-exception-invalid-receiver-type-class-java-lang-object-not-a-subtype-of) that describes the exception.
Also I put the stacktrace in the description

## Description

```java
 java.lang.BootstrapMethodError: call site initialization exception
 #011at java.lang.invoke.CallSite.makeSite(CallSite.java:341) ~[na:1.8.0_162]
 #011at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[na:1.8.0_162]
 #011at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[na:1.8.0_162]
 #011at org.zalando.logbook.httpclient.LocalRequest.getContentType(LocalRequest.java:109) ~[logbook-httpclient-1.8.1.jar!/:na]
 #011at org.zalando.logbook.Conditions.lambda$contentType$3(Conditions.java:54) ~[logbook-core-1.8.1.jar!/:na]
 #011at org.zalando.logbook.BodyReplacers.lambda$replaceBody$0(BodyReplacers.java:48) ~[logbook-core-1.8.1.jar!/:na]
 #011at org.zalando.logbook.BodyReplacer.lambda$null$0(BodyReplacer.java:21) ~[logbook-api-1.8.1.jar!/:na]
 #011at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_162]
 #011at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:1.8.0_162]
 #011at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_162]
 #011at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_162]
 #011at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_162]
 #011at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_162]
 #011at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_162]
 #011at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_162]
 #011at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_162]
 #011at org.zalando.logbook.BodyReplacer.lambda$compound$1(BodyReplacer.java:23) ~[logbook-api-1.8.1.jar!/:na]
 #011at org.zalando.logbook.RawRequestFilters.lambda$replaceBody$0(RawRequestFilters.java:24) ~[logbook-core-1.8.1.jar!/:na]
 #011at org.zalando.logbook.DefaultLogbook.write(DefaultLogbook.java:44) ~[logbook-core-1.8.1.jar!/:na]
 #011at org.zalando.logbook.httpclient.LogbookHttpRequestInterceptor.process(LogbookHttpRequestInterceptor.java:29) ~[logbook-httpclient-1.8.1.jar!/:na]
 #011at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133) ~[httpcore-4.4.6.jar!/:4.4.6]
 #011at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]
 #011at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:99) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.zalando.riptide.spring.PluginInterceptors$Adapter.lambda$intercept$0(PluginInterceptors.java:49) ~[riptide-spring-boot-starter-2.8.0.jar!/:na]
 #011at org.zalando.riptide.OriginalStackTracePlugin.lambda$prepare$1(OriginalStackTracePlugin.java:27) ~[riptide-core-2.8.0.jar!/:na]
 #011at org.zalando.riptide.spring.PluginInterceptors$Adapter.intercept(PluginInterceptors.java:61) ~[riptide-spring-boot-starter-2.8.0.jar!/:na]
 #011at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
 #011at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:287) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
```

## Expected Behavior
The exception should not be thrown and the call executed should be logged

## Actual Behavior
The call fails 

## Steps to Reproduce

```java
restTemplate.getForEntity(some_url,somePojo[].class).getBody()
```

## Context
just upgrading from an old version, for a project that does 

## Your Environment
Java8 spring-boot 1.5.7
* Version used: 2.8.1/2.8.0(failed) 2.7.1 (succeed)

**Comment by whiskeysierra** [comment]
The stack trace looks like this is a logbook issue. Can you prepare a sample project to reproduce this?

**Comment by mazenmelouk** [comment]
[bugidentifyingsample.zip](https://github.com/zalando/riptide/files/2159992/bugidentifyingsample.zip)

Not the very best piece of code but running `mvn test` gets the same exception

**Comment by whiskeysierra** [comment]
IntelliJ actually produces a root cause:

```
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 80 more
```

Looks like we are running into a dependency issue with Apache Http Client. See [release notes](https://archive.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES.txt) for version 4.4.9:

> * HTTPCORE-499: Make interface Header extend NameValuePair.
  Contributed by Gary Gregory <ggregory at apache.org>

You can workaround this by specifying a concrete http client/core version until we release riptide, logbook and tracer with a matching version for http core and client:

```xml
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.5</version>
</dependency>

<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4.9</version>
</dependency>
```

That gives me another error, but it looks OK to me:

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8011/api/items": Connect to localhost:8011 [localhost/127.0.0.1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:8011 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
```
