### ISSUE TITLE
Unable to start the application with riptide

### ISSUE THREAD

**Issue by divinedragon** [zalando/riptide#462]
I have a minimalist application with just riptide added to the Spring Boot Application(v2.0.3), and it is failing to Start. It gives me below exception:

```
Caused by: java.lang.ClassNotFoundException: org.zalando.riptide.spring.RiptideSettings
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	... 25 common frames omitted
```

## Description
As per the documentation on the Home Page, the application should run with just adding the below dependency. Seems like, I need to add some additional dependency.

## Expected Behavior
The application should start with just the main dependency, or the documentation should be updated to list additional dependencies required.

## Actual Behavior
The application fails to start.

## Steps to Reproduce
Here is the link to the Maven Project - https://github.com/divinedragon/riptide-demo
I am using latest Spring Boot - 2.0.3

**Comment by whiskeysierra** [comment]
The spring boot starter was split up to support Spring Boot 1.x and 2.x. The class is now contained in `riptide-spring-boot-api`. Maven should automatically resolve the transitive dependency for you and include it in the classpath. Dependency is correctly declared here https://github.com/zalando/riptide/blob/2.8.1/riptide-spring-boot-starter/pom.xml#L94. Can you verify why that dependency is excluded for you?

**Comment by divinedragon** [comment]
So, maven complains that my pom for `riptide-spring-boot-starter` is invalid.

```
[WARNING] The POM for org.zalando:riptide-spring-boot-starter:jar:2.8.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```
