### ISSUE TITLE
riptide-spring-boot-starter vs. tracing-lightstep-spring-boot-starter

### ISSUE THREAD

**Issue by harti2006** [zalando/riptide#542]
## Description
In a project, I'm using the `riptide-spring-boot-starter` without [Tracer](https://github.com/zalando/tracer) integration. When I included `tracing-lightstep-spring-boot-starter` my app failed to start with the following exception:

    java.lang.NoClassDefFoundError: org/zalando/tracer/concurrent/TracingExecutors
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.trace(DefaultRiptideRegistrar.java:378) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.registerExecutor(DefaultRiptideRegistrar.java:102) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.lambda$registerAsyncClientHttpRequestFactory$1(DefaultRiptideRegistrar.java:94) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.Registry.registerIfAbsent(Registry.java:72) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.registerAsyncClientHttpRequestFactory(DefaultRiptideRegistrar.java:85) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.lambda$register$0(DefaultRiptideRegistrar.java:73) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65) ~[guava-27.0-jre.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.register(DefaultRiptideRegistrar.java:72) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.RiptidePostProcessor.postProcessBeanDefinitionRegistry(RiptidePostProcessor.java:47) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]

The [offending part](https://github.com/zalando/riptide/blob/ea91da2c6a9f899f1bab2499aa3a29b08ae7186f/riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java#L397) of the code is:
```java
private BeanMetadataElement trace(final String executor) {
    if (registry.isRegistered("tracer")) {
        return genericBeanDefinition(TracingExecutors.class)
                .setFactoryMethod("preserve")
                .addConstructorArgReference(executor)
                .addConstructorArgReference("tracer")
                .getBeanDefinition();
    } else {
        return ref(executor);
    }
}
```

The opentracing autoconfiguration adds a bean called "tracer" to the context.  As soon as there is any bean with the name "tracer" available, Riptide will try to configure its clients to use it. However the Riptide-Tracer is not compatible with the OpenTracing Tracer and leads to that exception. 

## Expected Behavior
Riptide should not confuse the OpenTracing tracer with its own one.

## Possible Fix
Instead of referencing beans by name, Riptide should try to fetch them by type and probably also check if the class is available.

## Context
Using both Riptide and OpenTracing in the same project and while making use of the auto-configuration.

## Your Environment
* Version used:
  ```
  <riptide.version>2.10.1</riptide.version>
  <tracing-lightstep-spring-boot-starter.version>0.1.0</tracing-lightstep-spring-boot-starter.version>
  ```
* Link to your project: internal

**Comment by whiskeysierra** [comment]
> Instead of referencing beans by name, Riptide should try to fetch them by type and probably also check if the class is available.

I tried that a long time ago, but the riptide spring boot starter is a bean definition post processor so there are no beans yet, just definitions. Unfortunately spring doesn't offer an easy way to inspect the class/type, maybe because the don't even know themselves at that point. Feel free to prepare a pull request to change it. I tried and failed.

**Comment by harti2006** [comment]
Ok, so what about using a more qualified name instead, than just "tracer", e.g. "zalandoTracer"?

**Comment by whiskeysierra** [comment]
That would be require a change in tracer as well and would be a breaking change.

**Comment by harti2006** [comment]
Yeah, another non-breaking alternative would be to check if the class `TracingExecutors` is actually available and skip if not. 
It would still lead to problems when both OpenTracing and Tracer are used at the same time, but at least handle situations where only one is present, gracefully.

**Comment by whiskeysierra** [comment]
> It would still lead to problems when both OpenTracing and Tracer are used at the same time

True, but since it already fails right now (duplicate bean name I guess), that wouldn't make it worse.

> check if the class `TracingExecutors` is actually available

Can you prepare a pull request for this?

**Comment by harti2006** [comment]
Let me try...
