### ISSUE TITLE
Runtime failure for logbook and riptide integration

### ISSUE THREAD

**Issue by RohanNg** [zalando/riptide#773]
Failure at runtime occur when enabling latest LogBook version `2.0.0-RC.3` and Riptide latest version `3.0.0-RC.4` in spring boot `2.1.7.RELEASE`.

In our project we implemented a custom LogBook Sink.

Stack trace:

```kotlin
Caused by: java.lang.UnsupportedOperationException: null
        at org.zalando.riptide.httpclient.StreamingApacheClientHttpRequest.getBody(StreamingApacheClientHttpRequest.java:57)
        at org.zalando.riptide.logbook.TeeHttpOutputMessage.<init>(TeeHttpOutputMessage.java:17)
        at org.zalando.riptide.logbook.LocalRequest$Offering.buffer(LocalRequest.java:78)
        at org.zalando.riptide.logbook.LocalRequest.lambda$writeTo$1(LocalRequest.java:197)
        at org.zalando.fauxpas.ThrowingFunction.apply(ThrowingFunction.java:19)
        at java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:179)
        at org.zalando.riptide.logbook.LocalRequest.writeTo(LocalRequest.java:196)
        at org.zalando.riptide.logbook.LogbookPlugin$LogbookEntity.writeTo(LogbookPlugin.java:55)
        at org.zalando.riptide.BlockingIO.execute(BlockingIO.java:29)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.AsyncPlugin.lambda$aroundNetwork$3(AsyncPlugin.java:26)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.logbook.LogbookPlugin.lambda$aroundNetwork$1(LogbookPlugin.java:35)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.faults.TransientFaultPlugin.lambda$aroundNetwork$0(TransientFaultPlugin.java:25)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.auth.AuthorizationPlugin.lambda$aroundNetwork$0(AuthorizationPlugin.java:21)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.SerializationPlugin.lambda$aroundSerialization$0(SerializationPlugin.java:16)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.DispatchPlugin.lambda$aroundDispatch$1(DispatchPlugin.java:14)
        at org.zalando.riptide.GuardedRequestExecution.execute(GuardedRequestExecution.java:18)
        at org.zalando.riptide.AsyncPlugin.lambda$null$0(AsyncPlugin.java:19)
        at org.zalando.fauxpas.ThrowingSupplier.get(ThrowingSupplier.java:19)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Expected behavior is that the integration works.

**Comment by whiskeysierra** [comment]
Looks like `riptide-logbook` doesn't properly supporting streaming. Either you disable logbook (`riptide.my-client.logging.enabled: false`) or change the connection mode from streaming to buffering (`riptide.defaults.connections.mode: buffering`).

**Comment by RohanNg** [comment]
Thank for your feedback. I switched to buffering and it works fine.

Now I wonder if what proper support for streaming here would be. Is it feasible to get response body when `TeeHttpOutputMessage` was initialized? If not, maybe we can return some dummy string instead of throwing the error?

**Comment by whiskeysierra** [comment]
The difference between buffering and streaming is very small if your message bodies are not outrageously huge. I'll fix this properly in the next weeks.

A small remark: The fundamental issue here is that Spring is violating the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). Another reason why proper software design matters. :wink:
