### ISSUE TITLE
Failsafe is mandatory dependency since RC.6

### ISSUE THREAD

**Issue by fatroom** [zalando/riptide#841]
## Description
Seems we got again the problem with optionality of dependency. 
Build where only auto starter is included fails with NoClassDefFoundError

## Expected Behavior
Default spring starter project with riptide-spring-boot-starter should pass the ContextLoad test
## Actual Behavior
Test fails with 
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.zalando.riptide.autoconfigure.RiptidePostProcessor]: Factory method 'riptidePostProcessor' threw exception; nested exception is java.lang.NoClassDefFoundError: net/jodah/failsafe/Policy
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: net/jodah/failsafe/Policy
	at org.zalando.riptide.autoconfigure.RiptideAutoConfiguration.riptidePostProcessor(RiptideAutoConfiguration.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 43 more
```
## Possible Fix
Check what constructor referenced unconditionally and got Policy as argument.

## Steps to Reproduce
1. Create maven spring boot project via start.spring.io
2. Add riptide-spring-boot-starter as dependency
3. Run ./mvnw test
4.

## Your Environment
* Version used: RC.6-RC-8
* Link to your project:

**Comment by whiskeysierra** [comment]
Here we go again... :see_no_evil:

**Comment by fatroom** [comment]
I suspect #797 #783 or #784 as reason. 
Will try to investigate over the week-end. 

Fancy fact - I discovered this while was trying to reproduce another issue: there's something fishy going with dependency management, got unexpected failures in the project on boot 2.1 (spring-data) and latest riptide. Will report that separately when figure out clear conditions.

**Comment by fatroom** [comment]
#784 is the source

**Comment by fatroom** [comment]
I'm out of my depth here.
Tried to playground with debugging options and figured out that verification of `DefaultRiptideRegistrar` fails. 
(options used: -XX:-TraceClassLoadingPreorder -XX:+TraceClassResolution -XX:+TraceClassLoading)

```
[3.027s][debug  ][class,resolve] org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar org.springframework.beans.BeanMetadataElement DefaultRiptideRegistrar.java (verification)
[3.027s][debug  ][class,resolve] java.lang.NoClassDefFoundError java.lang.LinkageError NoClassDefFoundError.java:59
```

`javap -v` gives suspicios reference:
```
    #221 = InterfaceMethodref #229.#800    // org/zalando/riptide/failsafe/RequestPolicy.of:(Lnet/jodah/failsafe/Policy;)Lorg/zalando/riptide/failsafe/RequestPolicy;
   #800 = NameAndType        #809:#1146   // of:(Lnet/jodah/failsafe/Policy;)Lorg/zalando/riptide/failsafe/RequestPolicy;
  #1146 = Utf8               (Lnet/jodah/failsafe/Policy;)Lorg/zalando/riptide/failsafe/RequestPolicy;
```
Seems that somehow Registar via RequestPolicy interface was directly linked with failsafe.Policy

Now sure how to fix this. Rollback #784? 
Rewrite in someway RequestPolicy to omit the reference to the Policy?

@whiskeysierra @lukasniemeier-zalando WDYT?

**Comment by jrehwaldt** [comment]
Maybe it's enough to get rid of [this](https://github.com/zalando/riptide/pull/784/files#diff-cc11a6c99c01ab43ca33d8be0682b278R463-R465) inline reference to `RequestFactory`? Just an idea; haven't tried it.

**Comment by whiskeysierra** [comment]
I'm not totally happy with the current state of `RequestPolicy` and `RetryRequestPolicy` anyway. But since I don't have a good idea how to make it better, @fatroom are you up to propose a change to the current code base in order to get rid of the undesired dependency? Ideally with a test that reproduces this (separate surefire execution?).

**Comment by fatroom** [comment]
I was trying few times to tackle this issue, but haven't found "easy" way to fix this without rollback the changes that was introducing this issue or major overhaul of the policies registration.
Generally to make things independent we need to "hide" usage of this class in depth of failsafe plugin (ie maybe delegating wrappers would be way to go?)

**Comment by whiskeysierra** [comment]
If you provide a failing test, I'll fix it :grin:

**Comment by fatroom** [comment]
@whiskeysierra there's the test for you ;) #892

**Comment by whiskeysierra** [comment]
@jrehwaldt Your suggestion was spot-on! Getting rid of this direct reference to `RequestPolicy` did the trick. (Locally at least :crossed_fingers:)
