### ISSUE TITLE
Disable tracing does not work

### ISSUE THREAD

**Issue by jadetang** [zalando/riptide#945]
## Description

I try to run the demo from the riptide spring starter. The Springboot throws an exception during the bootstrap. 

My config in yaml
```
riptide.clients:
  default:
    tracing:
      enabled: false
  example:
    base-url: http://example.com
    connections:
      connect-timeout: 150 milliseconds
      socket-timeout: 100 milliseconds
      time-to-live: 30 seconds
      max-per-route: 16
    tracing:
      enabled: false
```
my pom.xml
```
		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>riptide-spring-boot-starter</artifactId>
			<version>3.0.0-RC.13</version>
		</dependency>
``` 

and the stack trace
```
2020-06-09 21:08:05.115 ERROR 24308 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: io/opentracing/contrib/concurrent/TracedExecutorService
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.registerExecutor(DefaultRiptideRegistrar.java:173) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.createExecutor(DefaultRiptideRegistrar.java:150) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.lambda$registerHttp$1(DefaultRiptideRegistrar.java:109) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.Registry.lambda$registerIfAbsent$1(Registry.java:33) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
	at org.zalando.riptide.autoconfigure.Registry.registerIfAbsent(Registry.java:32) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.Registry.registerIfAbsent(Registry.java:28) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.registerHttp(DefaultRiptideRegistrar.java:104) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.lambda$register$0(DefaultRiptideRegistrar.java:97) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185) ~[guava-28.1-jre.jar:na]
	at org.zalando.riptide.autoconfigure.DefaultRiptideRegistrar.register(DefaultRiptideRegistrar.java:96) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.zalando.riptide.autoconfigure.RiptidePostProcessor.postProcessBeanDefinitionRegistry(RiptidePostProcessor.java:40) ~[riptide-spring-boot-autoconfigure-3.0.0-RC.13.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at de.zalando.cat.productionstatus.ProductionStatusApiApplication.main(ProductionStatusApiApplication.java:12) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: io.opentracing.contrib.concurrent.TracedExecutorService
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 23 common frames 
```

## Expected Behavior
The application should start. 
## Actual Behavior
The application fails to start.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I try to use riptide in my project.

## Your Environment

* Version used:
`3.0.0-RC.13`
* Link to your project:
This is a Zalando internal one.

**Comment by fatroom** [comment]
Thanks for the report, will check the behaviour

**Comment by jadetang** [comment]
> Thanks for the report, will check the behaviour

I also have this in my project, not sure it is relevant.
```
		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>opentracing-toolbox-spring-boot-starter</artifactId>
			<version>3.0.0-RC.0</version>
		</dependency>
```

**Comment by fatroom** [comment]
@jadetang can you please provide full pom.xml?

I can not reproduce the issue on clean pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>


		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>riptide-spring-boot-starter</artifactId>
			<version>3.0.0-RC.13</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by jadetang** [comment]
@fatroom 
Hi, I checked my POM. I think the issue is caused by something else. 
Sorry for the confusion. I will close the issue.
